.\" Copyright (c) 1997 Juan Cespedes <cespedes@debian.org>
.\" This file is covered by the GNU GPL
.TH ltrace 1 
.SH NAME
ltrace \- A library call tracer

.SH SYNOPSIS
.B ltrace
.I "[-difLSttt] [-a column] [-s strsize] [-o filename] [-u username] [-p pid] ... [command [arg ...]]"

.SH DESCRIPTION
.B ltrace
is a program that simply runs the specified
.I command
until it exits.  It intercepts and records the dynamic library calls
which are called by the executed process and the signals which are
received by that process.
.PP
Its use is very similar to
.BR strace(1) .

.SH OPTIONS
.TP
.I \-d
Increase the debugging level.
.TP
.I \-i
Print the instruction pointer at the time of the library call.
.TP
.I \-f
Trace child processes as they are created by
currently  traced processes as a result of the fork(2)
or clone(2) system calls.
The new process is attached as soon as its pid is known.
.TP
.I \-L
DON'T display library calls (use it with the
.I \-S
option).
.TP
.I \-S
Display system calls as well as library calls
.TP
.I \-t
Prefix each line of the trace with the time of day.
.TP
.I \-tt
If given twice, the time printed will include the microseconds.
.TP
.I \-ttt
If given thrice, the time printed will include the microseconds and
the leading portion will be printed as the number of seconds since the
epoch.
.TP
.I \-a column
Align return values in a secific column (default column 50).
.TP
.I \-s
Specify the maximum string size to print (the default is 32).
.TP
.I \-o filename
Write the trace output to the file
.I filename
rather than to stderr.
.TP
.I \-u username
Run command with the userid, groupid and supplementary groups of
.IR username .
This option is only useful when running as root and enables the
correct execution of setuid and/or setgid binaries.
.TP
.I \-p pid
Attach to the process with the process ID
.I pid
and begin tracing.

.SH BUGS
At the moment, there are too many bugs to list here.
.PP
If you like to report a bug, send a notice to the author, or use the
.BR bug(1)
program if you are under Debian GNU/Linux.

.SH FILES
.TP
.I /etc/ltrace.conf
System configuration file
.TP
.I ~/.ltrace.conf
Personal config file, overrides
.I /etc/ltrace.conf

.SH AUTHOR
Juan Cespedes <cespedes@debian.org>

.SH "SEE ALSO"
.BR strace(1) ,
.BR ptrace(2)

