#!/bin/sh -e

# Create ltrace-${version}.tar.gz from a GIT repository

if [ ! -d .git -o ! -f libltrace.c ]
then
  echo "This must be called inside a ltrace GIT repository" 1>&2
  exit 1
fi

VERSION=$( cat VERSION )

echo Building ltrace-$VERSION.tar.gz ...
rm -rf ltrace-$VERSION
git clone ./ ltrace-$VERSION >/dev/null
GZIP=-9 tar --exclude .git -zcf ltrace-$VERSION.tar.gz ltrace-$VERSION
rm -rf ltrace-$VERSION
echo Done.

