    "0",			/*Linux +   0*/
    "exit",			/*Linux +   1*/
    "fork",			/*Linux +   2*/
    "read",			/*Linux +   3*/
    "write",			/*Linux +   4*/
    "open",			/*Linux +   5*/
    "close",			/*Linux +   6*/
    "waitpid",			/*Linux +   7*/
    "creat",			/*Linux +   8*/
    "link",			/*Linux +   9*/
    "unlink",			/*Linux +  10*/
    "execve",			/*Linux +  11*/
    "chdir",			/*Linux +  12*/
    "time",			/*Linux +  13*/
    "mknod",			/*Linux +  14*/
    "chmod",			/*Linux +  15*/
    "lchown",			/*Linux +  16*/
    "break",			/*Linux +  17*/
    "unused18",			/*Linux +  18*/
    "lseek",			/*Linux +  19*/
    "getpid",			/*Linux +  20*/
    "mount",			/*Linux +  21*/
    "umount",			/*Linux +  22*/
    "setuid",			/*Linux +  23*/
    "getuid",			/*Linux +  24*/
    "stime",			/*Linux +  25*/
    "ptrace",			/*Linux +  26*/
    "alarm",			/*Linux +  27*/
    "unused28",			/*Linux +  28*/
    "pause",			/*Linux +  29*/
    "utime",			/*Linux +  30*/
    "stty",			/*Linux +  31*/
    "gtty",			/*Linux +  32*/
    "access",			/*Linux +  33*/
    "nice",			/*Linux +  34*/
    "ftime",			/*Linux +  35*/
    "sync",			/*Linux +  36*/
    "kill",			/*Linux +  37*/
    "rename",			/*Linux +  38*/
    "mkdir",			/*Linux +  39*/
    "rmdir",			/*Linux +  40*/
    "dup",			/*Linux +  41*/
    "pipe",			/*Linux +  42*/
    "times",			/*Linux +  43*/
    "prof",			/*Linux +  44*/
    "brk",			/*Linux +  45*/
    "setgid",			/*Linux +  46*/
    "getgid",			/*Linux +  47*/
    "signal",			/*Linux +  48*/
    "geteuid",			/*Linux +  49*/
    "getegid",			/*Linux +  50*/
    "acct",			/*Linux +  51*/
    "umount2",			/*Linux +  52*/
    "lock",			/*Linux +  53*/
    "ioctl",			/*Linux +  54*/
    "fcntl",			/*Linux +  55*/
    "mpx",			/*Linux +  56*/
    "setpgid",			/*Linux +  57*/
    "ulimit",			/*Linux +  58*/
    "unused59",			/*Linux +  59*/
    "umask",			/*Linux +  60*/
    "chroot",			/*Linux +  61*/
    "ustat",			/*Linux +  62*/
    "dup2",			/*Linux +  63*/
    "getppid",			/*Linux +  64*/
    "getpgrp",			/*Linux +  65*/
    "setsid",			/*Linux +  66*/
    "sigaction",			/*Linux +  67*/
    "sgetmask",			/*Linux +  68*/
    "ssetmask",			/*Linux +  69*/
    "setreuid",			/*Linux +  70*/
    "setregid",			/*Linux +  71*/
    "sigsuspend",			/*Linux +  72*/
    "sigpending",			/*Linux +  73*/
    "sethostname",		/*Linux +  74*/
    "setrlimit",			/*Linux +  75*/
    "getrlimit",			/*Linux +  76*/
    "getrusage",			/*Linux +  77*/
    "gettimeofday",		/*Linux +  78*/
    "settimeofday",		/*Linux +  79*/
    "getgroups",			/*Linux +  80*/
    "setgroups",			/*Linux +  81*/
    "reserved82",			/*Linux +  82*/
    "symlink",			/*Linux +  83*/
    "unused84",			/*Linux +  84*/
    "readlink",			/*Linux +  85*/
    "uselib",			/*Linux +  86*/
    "swapon",			/*Linux +  87*/
    "reboot",			/*Linux +  88*/
    "readdir",			/*Linux +  89*/
    "mmap",			/*Linux +  90*/
    "munmap",			/*Linux +  91*/
    "truncate",			/*Linux +  92*/
    "ftruncate",			/*Linux +  93*/
    "fchmod",			/*Linux +  94*/
    "fchown",			/*Linux +  95*/
    "getpriority",		/*Linux +  96*/
    "setpriority",		/*Linux +  97*/
    "profil",			/*Linux +  98*/
    "statfs",			/*Linux +  99*/
    "fstatfs",			/*Linux + 100*/
    "ioperm",			/*Linux + 101*/
    "socketcall",			/*Linux + 102*/
    "syslog",			/*Linux + 103*/
    "setitimer",			/*Linux + 104*/
    "getitimer",			/*Linux + 105*/
    "stat",			/*Linux + 106*/
    "lstat",			/*Linux + 107*/
    "fstat",			/*Linux + 108*/
    "unused109",			/*Linux + 109*/
    "iopl",			/*Linux + 110*/
    "vhangup",			/*Linux + 111*/
    "idle",			/*Linux + 112*/
    "vm86",			/*Linux + 113*/
    "wait4",			/*Linux + 114*/
    "swapoff",			/*Linux + 115*/
    "sysinfo",			/*Linux + 116*/
    "ipc",			/*Linux + 117*/
    "fsync",			/*Linux + 118*/
    "sigreturn",			/*Linux + 119*/
    "clone",			/*Linux + 120*/
    "setdomainname",		/*Linux + 121*/
    "uname",			/*Linux + 122*/
    "modify_ldt",			/*Linux + 123*/
    "adjtimex",			/*Linux + 124*/
    "mprotect",			/*Linux + 125*/
    "sigprocmask",		/*Linux + 126*/
    "create_module",		/*Linux + 127*/
    "init_module",		/*Linux + 128*/
    "delete_module",		/*Linux + 129*/
    "get_kernel_syms",		/*Linux + 130*/
    "quotactl",			/*Linux + 131*/
    "getpgid",			/*Linux + 132*/
    "fchdir",			/*Linux + 133*/
    "bdflush",			/*Linux + 134*/
    "sysfs",			/*Linux + 135*/
    "personality",		/*Linux + 136*/
    "afs_syscall",		/*Linux + 137*/ /* Syscall for Andrew File System */
    "setfsuid",			/*Linux + 138*/
    "setfsgid",			/*Linux + 139*/
    "_llseek",			/*Linux + 140*/
    "getdents",			/*Linux + 141*/
    "_newselect",			/*Linux + 142*/
    "flock",			/*Linux + 143*/
    "msync",			/*Linux + 144*/
    "readv",			/*Linux + 145*/
    "writev",			/*Linux + 146*/
    "cacheflush",			/*Linux + 147*/
    "cachectl",			/*Linux + 148*/
    "sysmips",			/*Linux + 149*/
    "unused150",			/*Linux + 150*/
    "getsid",			/*Linux + 151*/
    "fdatasync",			/*Linux + 152*/
    "_sysctl",			/*Linux + 153*/
    "mlock",			/*Linux + 154*/
    "munlock",			/*Linux + 155*/
    "mlockall",			/*Linux + 156*/
    "munlockall",			/*Linux + 157*/
    "sched_setparam",		/*Linux + 158*/
    "sched_getparam",		/*Linux + 159*/
    "sched_setscheduler",		/*Linux + 160*/
    "sched_getscheduler",		/*Linux + 161*/
    "sched_yield",		/*Linux + 162*/
    "sched_get_priority_max",	/*Linux + 163*/
    "sched_get_priority_min",	/*Linux + 164*/
    "sched_rr_get_interval",	/*Linux + 165*/
    "nanosleep",			/*Linux + 166*/
    "mremap",			/*Linux + 167*/
    "accept",			/*Linux + 168*/
    "bind",			/*Linux + 169*/
    "connect",			/*Linux + 170*/
    "getpeername",		/*Linux + 171*/
    "getsockname",		/*Linux + 172*/
    "getsockopt",			/*Linux + 173*/
    "listen",			/*Linux + 174*/
    "recv",			/*Linux + 175*/
    "recvfrom",			/*Linux + 176*/
    "recvmsg",			/*Linux + 177*/
    "send",			/*Linux + 178*/
    "sendmsg",			/*Linux + 179*/
    "sendto",			/*Linux + 180*/
    "setsockopt",			/*Linux + 181*/
    "shutdown",			/*Linux + 182*/
    "socket",			/*Linux + 183*/
    "socketpair",			/*Linux + 184*/
    "setresuid",			/*Linux + 185*/
    "getresuid",			/*Linux + 186*/
    "query_module",		/*Linux + 187*/
    "poll",			/*Linux + 188*/
    "nfsservctl",			/*Linux + 189*/
    "setresgid",			/*Linux + 190*/
    "getresgid",			/*Linux + 191*/
    "prctl",			/*Linux + 192*/
    "rt_sigreturn",		/*Linux + 193*/
    "rt_sigaction",		/*Linux + 194*/
    "rt_sigprocmask",		/*Linux + 195*/
    "rt_sigpending",		/*Linux + 196*/
    "rt_sigtimedwait",		/*Linux + 197*/
    "rt_sigqueueinfo",		/*Linux + 198*/
    "rt_sigsuspend",		/*Linux + 199*/
    "pread",			/*Linux + 200*/
    "pwrite",			/*Linux + 201*/
    "chown",			/*Linux + 202*/
    "getcwd",			/*Linux + 203*/
    "capget",			/*Linux + 204*/
    "capset",			/*Linux + 205*/
    "sigaltstack",		/*Linux + 206*/
    "sendfile",			/*Linux + 207*/
    "getpmsg",			/*Linux + 208*/
    "putpmsg",			/*Linux + 209*/
    "mmap2",			/*Linux + 210*/
    "truncate64",			/*Linux + 211*/
    "ftruncate64",		/*Linux + 212*/
    "stat64",			/*Linux + 213*/
    "lstat64",			/*Linux + 214*/
    "fstat64",			/*Linux + 215*/
    "pivot_root",			/*Linux + 216*/
    "mincore",			/*Linux + 217*/
    "madvise",			/*Linux + 218*/
    "getdents64",			/*Linux + 219*/
    "fcntl64",			/*Linux + 220*/
    "security",			/*Linux + 221*/
    "gettid",			/*Linux + 222*/
    "readahead",			/*Linux + 223*/
    "setxattr",			/*Linux + 224*/
    "lsetxattr",			/*Linux + 225*/
    "fsetxattr",			/*Linux + 226*/
    "getxattr",			/*Linux + 227*/
    "lgetxattr",			/*Linux + 228*/
    "fgetxattr",			/*Linux + 229*/
    "listxattr",			/*Linux + 230*/
    "llistxattr",			/*Linux + 231*/
    "flistxattr",			/*Linux + 232*/
    "removexattr",		/*Linux + 233*/
    "lremovexattr",		/*Linux + 234*/
    "fremovexattr",		/*Linux + 235*/
    "tkill",			/*Linux + 236*/
    "sendfile64",			/*Linux + 237*/
    "futex",			/*Linux + 238*/
    "sched_setaffinity",		/*Linux + 239*/
    "sched_getaffinity",		/*Linux + 240*/
