#define BREAKPOINT_VALUE {0xcc}
#define BREAKPOINT_LENGTH 1
#define DECR_PC_AFTER_BREAK 1

#define LT_ELFCLASS	ELFCLASS32
#define LT_ELF_MACHINE	EM_386

#define PLTs_INIT_BY_HERE NULL
#define E_ENTRY_NAME    "_start"
