#define BREAKPOINT_VALUE { 0x80, 0x00, 0x00, 0x00 }
#define BREAKPOINT_LENGTH 4
#define DECR_PC_AFTER_BREAK 4

#define LT_ELFCLASS     ELFCLASS64
#define LT_ELF_MACHINE  EM_ALPHA
#define LT_ELFCLASS2    ELFCLASS64
#define LT_ELF_MACHINE2	EM_FAKE_ALPHA
